FROM golang:1.22.3-bullseye

COPY . ./src/app
WORKDIR /go/src/app

# TODO: make ljrickard repo private
# including -u to get latest
RUN go get -d -v -u ./...
RUN go install -v ./...

# clean dependencies
RUN go mod tidy 

EXPOSE 8080

# Run
CMD ["main"]
